### ISSUE TITLE
Bug when used with another plugin (CSVLint and ComparePlus)

### ISSUE THREAD

**Issue by carlos-esteves** [BdR76/CSVLint#73] opened 2023-07-19 12:33 UTC
After to do "Compare" and stop this there are a "black line" that not disappear from cursor. If I do "Plugins -> CSVLint -> Settings -> Cancel" the BUG (the black line cursor) disappear.

**Comment by BdR76** [comment] 2023-07-19 15:06
Thanks, I hadn't though about this but closing the Settings form (Cancel or OK doesn't matter) will also call the [RefreshFromSettings()](https://github.com/BdR76/CSVLint/blob/master/CSVLintNppPlugin/Main.cs#L183), to update some variables for the `TwoDigitYearMax` and `TransparentCursor` settings.

I don't have the time to work on the plug-in at the moment, but you're right this is a good tip 👍

**Comment by BdR76** [comment] 2023-07-19 15:06
Duplicate of #68

**Closed** 2023-07-19 15:10 UTC
Labels: duplicate
