### ISSUE TITLE
Feature request/bugfix: Reformat for column width should account for column title width as well

### ISSUE THREAD

**Issue by SeanMirrsen** [BdR76/CSVLint#12] opened 2022-01-14 09:42 UTC
I'm not sure whether or not it's intended behavior, but for some reason right now only the data in the column itself, is taken into account when determining column width for the reformat. This ends up breaking the formatting when the title is longer than the longest data entry in the column, i.e. you have a column title of "tier", and only single-digit integer values. Or any title on an empty column.

If it's a bug, and it makes a difference for reproduction purposes, I'm on Windows 8 (not 8.1) x64, NP++ v8.2 64-bit.

**Comment by BdR76** [comment] 2022-03-12 11:26
It wasn't intended behavior, definitely a bug. Thanks for reporting the issue, it's fixed in the v0.4.5 update.

**Closed by BdR76** 2022-03-12 11:26 UTC
