### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Friedi** [BdR76/CSVLint#65] opened 2023-04-27 15:57 UTC
**Notepad++:** 8.5.2 (x64)
**CSVLint:** 0.4.6.3

When I open the following non csv conform text file and do "detect columns" (with automatic unchecked), and hitting "ok" in the manual detection dialog, Notepad++ crashes with an infinite loop of unhandled exceptions. Only killing the notepad task closes it. 

[Preconditioning_working.csv](https://github.com/BdR76/CSVLint/files/11345736/Preconditioning_working.csv)
![CVInt Error](https://user-images.githubusercontent.com/3397608/234917291-98ceea08-cfea-41df-9988-971301bec1b3.png)

**Comment by BdR76** [comment] 2023-04-28 12:33
Thanks for posting the issue, but I can't reproduce this.

The file encoding in the bottom right says `UTF-8` so that should be ok, maybe it has to do with the Windows codepage setting? Can you post the text from the `? > Debug info` menu?

**Comment by Friedi** [comment] 2023-04-28 14:48
I see my description was not correct, sorry for that. The error occurs only if you click detect columns (uncheced automatic) and then "ok" for manually detection.

**Comment by BdR76** [comment] 2023-04-29 13:45
Oops can't believe I missed that one.. This has to do with the `DetectColumnWidths` setting, the bug happens when the "Columns positions" text box is empty. Work-around is to start the manual detect dialog, for one time select separator as `{fixed width}` and then enter anything like `1,2,3` in the "Columns positions" textbox and press OK. After that it should work again without crashing.

The issue is fixed now and will be available in the next release

**Comment by BdR76** [comment] 2023-04-30 20:32
@Friedi  fyi I've updated the [development DLL from here](https://github.com/BdR76/CSVLint/tree/master/CSVLintNppPlugin/bin) which includes this fix. If you are able to try this version then let me know if there are any other issues

**Closed** 2023-05-09 12:56 UTC
Labels: bug
