### ISSUE TITLE
Cannot work with foreign language

### ISSUE THREAD

**Issue by Chipmunk91** [BdR76/CSVLint#47] opened 2022-12-15 05:10 UTC
Hi team.

CSV Lint seems like not recognize foreign language.
Try to color following file, you can see the columns are not properly set.

[lint test.csv](https://github.com/BdR76/CSVLint/files/10233903/lint.test.csv)

![image](https://user-images.githubusercontent.com/87294250/207777891-7f41eec3-ed35-4369-a6cd-ce55655dcb97.png)

**Comment by BdR76** [comment] 2022-12-15 09:20
Thanks for the issue report, however I cannot reproduce this. When I open the file you sent, the syntax highlighting seems to work ok. I think this has to do with the file encoding and maybe a Windows 11 setting. Three things to check:

1) Which version of the plug-in do you use? You can check the menu `Plugins > CSV Lint > About` or also `? > Debug info`.

2) Are you using Windows 11? In version v0.4.6 there was an update for improved compatibility with the Windows UTF8 setting.

3) What is the file encoding? You can check in the bottom right of Notepad++, when I open the file it says `UTF-8-BOM`

![lint_test_foreign_test](https://user-images.githubusercontent.com/7793956/207820716-4fab9cdd-c17d-463b-992f-174ab9377106.png)

**Comment by BdR76** [comment] 2022-12-31 12:20
Let me know if this was solved with installing the newest plug-in version, I can't reproduce this so for now I'll have close this issue

**Closed by BdR76** 2022-12-31 12:20 UTC
